version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: ../.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

